config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    patch '/users/confirmation' => 'confirmations#confirm'
  end

  resources :customers
  root 'welcome#index'

  get 'campaigns' => 'campaigns#index'
  get 'campaigns/:id' => 'campaigns#show', as: :campaign
  get 'discounts' => 'discounts#index'
  get 'offers' => 'offers#index'
  get 'offers/:id' => 'offers#show', as: :offer
  post 'offers/:id/purchases' => 'offers#purchase', as: :offer_purchases
  get 'prices' => 'prices#index'
  get 'products' => 'products#index'
  get 'products/:id' => 'products#show', as: :product
  get 'profile' => 'users#show'
  patch 'profile' => 'users#update'
  get 'profile/edit' => 'users#edit'
  get 'publications' => 'publications#index'
  get 'publications/:id' => 'publications#show', as: :publication

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: :json } do
    get 'version' => 'api#version'
    namespace :v1 do
      get 'subscribers' => 'subscribers#index'
      get 'subscribers/:id' => 'subscribers#show'
    end
  end
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  has_many :offer_publications
  accepts_nested_attributes_for :offer_publications
  has_many :offers, through: :offer_publications
  accepts_nested_attributes_for :offers
  has_many :subscriptions
  validates :name, presence: true, uniqueness: true
  validates :website, presence: true
  validates :website, format: { with: URI.regexp }, if: 'website.present?'
  has_attached_file :image, styles: { large: '1020x768>', thumb: '100x100#' },
    convert_options: { thumb: '-strip -quality 75' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/}

  before_save :ensure_api_key_unique

  private

  def ensure_api_key_unique
    while Publication.where(api_key: api_key).where.not(id: id).exists?
      self.api_key = Devise.friendly_token
    end
  end
end

app/controllers/publications_controller.rb
class PublicationsController < InheritedResources::Base
  respond_to :html, :json, :xml
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/index.html.erb
<h3>Publications</h3>

<% @publications.each do |publication| %>
<figure class="thumbnail">
	<%= link_to (image_tag publication.image.url(:thumb)), publication %>
	<figcaption><%= link_to publication.name, publication %></figcaption>
</figure>
<% end %>

app/views/publications/show.html.erb
<div class="jumbotron">
    <h3><%= @publication.name %></h3>

    <%= link_to image_tag(@publication.image.url(:large), alt: @publication.name), @publication.website %>

    <div class="row"><div class="col-xs-12">
        <%= @publication.description.html_safe %>
    </div></div>
</div>

<div class="list-group">
    <% if @publication.offers.empty? then %>
       <button type="button" class="list-group-item list-group-item-warning">
           Not presently available as part of any current offer
       </button>
    <% else %>
        <button type="button" class="list-group-item list-group-item-info">Available with these offers</button>
        <% @publication.offers.each do |offer| %>
        <%= link_to offer.name, offer_path(offer), class: 'list-group-item' %>
        <% end %>
    <% end %>
</div>