config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    patch '/users/confirmation' => 'confirmations#confirm'
  end

  resources :customers
  root 'welcome#index'

  get 'campaigns' => 'campaigns#index'
  get 'campaigns/:id' => 'campaigns#show', as: :campaign
  get 'discounts' => 'discounts#index'
  get 'offers' => 'offers#index'
  get 'offers/:id' => 'offers#show', as: :offer
  post 'offers/:id/purchases' => 'offers#purchase', as: :offer_purchases
  get 'prices' => 'prices#index'
  get 'products' => 'products#index'
  get 'products/:id' => 'products#show', as: :product
  get 'profile' => 'users#show'
  patch 'profile' => 'users#update'
  get 'profile/edit' => 'users#edit'
  get 'publications' => 'publications#index'
  get 'publications/:id' => 'publications#show', as: :publication

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api, defaults: { format: :json } do
    get 'version' => 'api#version'
    namespace :v1 do
      get 'subscribers' => 'subscribers#index'
      get 'subscribers/:id' => 'subscribers#show'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # :omniauthable is also available
  devise :confirmable, :database_authenticatable, :lockable,
         :recoverable, :rememberable, :timeoutable, :trackable, :validatable

  has_many :customers
  accepts_nested_attributes_for :customers, allow_destroy: true
  has_many :subscriptions

  validates :name, presence: true
  before_validation :generate_password, on: :create

  def currency_name
    return if currency.blank?
    m = Money::Currency.new(currency)
    "#{m.name} (#{m.iso_code})"
  end

  def password_match?
    errors[:password] << "can't be blank" if password.blank?
    errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    errors[:password_confirmation] << 'does not match password' if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def generate_password
    self.password_confirmation = self.password = Devise.friendly_token if password.nil? || password.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_action :authenticate_user!
  before_action { @user = current_user }
  respond_to :html, :json, :xml
  rescue_from ActiveRecord::RecordInvalid, with: :show_errors

  def update
    flash.notice = 'Profile updated.  Thank you!' if current_user.update! user_params
    redirect_to action: :show
  end

  protected

  def show_errors(exception)
    flash.alert = exception.message
    render :edit
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :time_zone, :currency)
  end
end

app/views/users/_form.html.erb
<%= semantic_form_for @user, url: profile_path do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :email %><br>
    <%= f.input :time_zone, input_html: { class: 'form-control' },
        priority_zones: /Australia/, default: 'Melbourne' %><br>
    <%= f.input :currency, label: 'Preferred currency',
        collection: options_for_select(Configuration::CURRENCY_OPTIONS, @user.currency || 'AUD') %><br>
    <%= f.actions { f.action :submit, label: 'Update profile' } %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h3>Editing profile</h3>

<div class="row"><div class="col-sm-6"><%= render 'form' %></div></div>

<%= link_to profile_path do %>
  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&ensp;Show
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if @user.unconfirmed_email.present? %>
  <p>
    <strong>Unconfirmed email:</strong>
    <%= @user.unconfirmed_email %>
  </p>
<% end %>

<% if @user.time_zone.present? %>
  <p>
    <strong>Time zone:</strong>
    <%= @user.time_zone %>
  </p>
<% end %>

<% if @user.currency.present? %>
  <p>
    <strong>Preferred currency:</strong>
    <%= @user.currency_name %>
  </p>
<% end %>

<%= link_to profile_edit_path do %>
  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&ensp;Edit
<% end %>